### ISSUE TITLE
Program crash when selecting different quantizers.

### ISSUE THREAD

**Issue by Xeddius** [Pangamma/PixelStacker#22]
Program crashed when selecting different quantizers, here is the error report.
[pixelstacker-error-report.zip](https://github.com/Pangamma/PixelStacker/files/6511212/pixelstacker-error-report.zip)

**Comment by Pangamma** [comment]
@Xeddius  Try this build:
https://github.com/Pangamma/PixelStacker/releases/tag/1.16.5f

**Comment by Xeddius** [comment]
Fixed 👍🏻
