### ISSUE TITLE
[suggestion] pattern export / layers / color matching

### ISSUE THREAD

**Issue by EvilErwin** [Pangamma/PixelStacker#24]
Hi,
first of all: great projekt!
This is a very helpfull tool.
Thank you for putting your time into it.

I have three suggestions:

1) A pattern export / render-mode that uses symbols for the diffent block types.
I try to use your tool in survival without any mods.
I find it difficult at times to see the differences between block types.
Especially similar colored glass blocks next to each other.
Could you implement a "redner-mode" where every block type is representet by a symbol instead of the block texture?
See the image for reference.
![cross stitch pattern mario](https://user-images.githubusercontent.com/86203782/125407950-ae24c680-e3ba-11eb-9b2e-6e051e60aa89.png)
This is a pattern for cross stitching, but it shows what i have in mind.
Its a trivial example with very distinct colors so there is not much advantage in using symbols.
But if you have a image with very similar colors next to each other it would help.

2) Layer selection like in image editors.
When i render a image in your tool, with the 2. layer activatet, i have the following view options:
- Both layers (default)
- One layer at a time, upper layer (check "Toggle layer filter" + "One layer up")
- One layer at a time, lower layer (check "Toggle layer filter" + "One layer down")
I find it unintuitive to get to the different layers.
And having the options under "View"->"Layer Options" results in many clicks to change the layers.
I suggest a layer selection similar to those in image editors.
When the rendered image has layers this activates, otherwise deactivates.
There is a list in the UI with all the layers in it and a checkbox to activate / deactivate each layer:
☑Layer 1
☑Layer 2

With this all three view options are only one click away.
And everyone who used a image editor is familiar with the concept.
 
3) Color matching.
I have not looked into your code, so i don't know if you are already using this.
I had a project where i had to match colors similar to this tool.
In my online research i found different methods to calculate the difference between colors.
Those methods simulatet the human color reception with varying success.
subpar: Euclidean distance in RGB color space.
better: CIEDE2000 in CIELAB color space.
See the following link for reference:
https://en.wikipedia.org/wiki/Color_difference
I don't know which method your tool is using or if you already looked into different methods.
I only wanted to mention this in case you didn't know of this.
There is a chance to improve the render results by using other ways to calculate the color differnce.
Under the assumption that the limitet color palette of minecraft leaves room for improvement.

**Comment by Pangamma** [comment]
1. See what you mean as a way of providing support for people with partial or full color blindness. This will work for a low number of colors. I think the maximum total is something like 3,000+ different color combinations though. So I would need a lot of symbols. It would work well for a reduced color set though. Anything lower than 256 materials would be fine. 

If you right click one of the blocks in the output viewer, it should tell you what the materials are for that block. So you can at least do it on a block by block basis. Do you have a proposal for how to handle the high number of patterns that would be required for this approach? Maybe only the 50 most common blocks are given patterns. Maybe each block category would have its own category indicator, and then each block in the category list would have its own number. W0 for white wool as an example. What are your thoughts?

**Comment by Pangamma** [comment]
Can't add this without more info.
