### ISSUE TITLE
Error when saving rendered picture

### ISSUE THREAD

**Issue by B10Reaper** [Pangamma/PixelStacker#31]
[pixelstacker-error-report.zip](https://github.com/Pangamma/PixelStacker/files/7591819/pixelstacker-error-report.zip)
Nothing specific shows up other than saving this and suggesting to open an issue.

**Comment by Pangamma** [comment]
@B10Reaper  Does this happen every time with that image?

**Comment by Pangamma** [comment]
Aha, yes I see now. Haha. .schematic format is not yet supported. Will .schem work for you instead, or do you need .schematic?

**Comment by Pangamma** [comment]
Which program are you going to use to import the schematic file?

**Comment by B10Reaper** [comment]
***@***.*** <https://github.com/B10Reaper>  Does this happen every time with that image?

Yes, and with every image

 

> Aha, yes I see now. Haha. .schematic format is not yet supported. Will .schem work for you instead, or do you need .schematic?

What’s odd is this only happens on the new version, I went back to the old version no problem and got everything sorted. I can definitely use .schem instead, I didn’t think there was a difference besides the extension. 

>Which program are you going to use to import the schematic file?

I am using worldedit to import the schematic file. 

 

I just received these 3 all at once, let me know if you need any more information to troubleshoot, otherwise I’ll just save everything in .schem

**Comment by Pangamma** [comment]
Try this release:
https://www.spigotmc.org/resources/pixelstacker-photo-realistic-pixel-art-generator.46812/download?version=430277

**Comment by Pangamma** [comment]
Closing because of no followup. Assumed fixed.
