### ISSUE TITLE
Cannot proceed image

### ISSUE THREAD

**Issue by OliveOL98** [Pangamma/PixelStacker#33]
I tried to proceed an image, but it showed me this error
[pixelstacker-error-report.zip](https://github.com/Pangamma/PixelStacker/files/7831953/pixelstacker-error-report.zip)

**Comment by Pangamma** [comment]
@OliveOL98  How much RAM do you have? The image you're doing is 3000x2000 in size. Could take a small bit of memory.

**Comment by Pangamma** [comment]
I think this issue has been fixed. Tiling algorithms have come a long way since when they were first added.
