### ISSUE TITLE
[Feature Request] Support Saving As .litematic

### ISSUE THREAD

**Issue by 4rm4g3dd0n** [Pangamma/PixelStacker#45]
Litematica is a popular replacement for the mod Schematica on newer Minecraft versions (1.12+), it uses the `.litematic` file format which is similar to Sponge's file structure wise, more details on it [here.](https://github.com/maruohon/litematica/issues/53)

**Comment by Pangamma** [comment]
Mannnnn. Why they no support sponge schem format like worldedit does?

**Comment by Pangamma** [comment]
I do get this request very often though.

**Comment by Pangamma** [comment]
Ugh. Litematica file format is a flaming garbage heap. Really ugly to look at from code.

**Comment by Pangamma** [comment]
@4rm4g3dd0n Have you tried exporting to schem2 format and then loading that into litematica?

**Comment by Pangamma** [comment]
schem2 works.
