### ISSUE TITLE
Light blue glass does not exist as option

### ISSUE THREAD

**Issue by aria1th** [Pangamma/PixelStacker#47]
Other variants (terracotta, concrete) exists... but light blue glass does not exist

**Comment by aria1th** [comment]
as further research, advanced mode does not activate properly...

**Comment by Peregrine05** [comment]
I can confirm that light blue stained glass is missing.

**Comment by Pangamma** [comment]
Ah you are correct. Okay so that PR has been merged in. Just a matter of pushing out a release fix for it now. I'll include it in the next release. Right now I am a bit focused on the web demo of pixelstacker.

**Comment by Pangamma** [comment]
> as further research, advanced mode does not activate properly...

you use arrow keys and it does not activate? It is supposed to. It works for me. Join me on the discord, we can go more in-depth.
