### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by VantaRyza** [Pangamma/PixelStacker#59]
Schem files save, but when I want to load one, they don't show up, and any other attempt to load them fails.

Also, some images break when loaded resulting in wild lines of various colors and breaks in the image that shouldn't be there, but some load just fine. Please help.

![Screenshot 2023-07-16 183127](https://github.com/Pangamma/PixelStacker/assets/139722100/f54db0e2-3596-4acf-802b-ec6a6b2171b2)

**Comment by Pangamma** [comment]
Hahhh man. That's... probably a bug with one of the libraries I'm using.

**Comment by Pangamma** [comment]
Can you send me your source image? @VantaRyza

**Comment by Pangamma** [comment]
@VantaRyza Can you retry with the latest release?

**Comment by VantaRyza** [comment]
@Pangamma I just tried a couple of images and they seem to work now. I still have no idea what's up with the .schem files though.

**Comment by Pangamma** [comment]
@VantaRyza Glad the image is fixed. For the schem files, please create a separate issue for that with a description of what goes wrong, and how to reproduce, as well as the expected behavior. I'll take a look into it and see what I can do. Thanks.
