### ISSUE TITLE
Coloured clay is called terracotta now

### ISSUE THREAD

**Issue by Mysticlloyd** [Pangamma/PixelStacker#60]
I have noticed that coloured clay has yet to be changed to terracotta in pixelastacker, as you can see from the images below and the comparisons to in-game name.
![2023-08-04 (1)](https://github.com/Pangamma/PixelStacker/assets/34624125/86e358bd-33c6-49eb-b53f-b6350d331a1c)
![2023-08-04 (2)](https://github.com/Pangamma/PixelStacker/assets/34624125/3e6866e7-baf5-4767-8e30-e2afa282ae74)
![2023-08-04](https://github.com/Pangamma/PixelStacker/assets/34624125/44cb050f-0fde-465f-b905-e2861ea012a7)
![2023-08-04 (3)](https://github.com/Pangamma/PixelStacker/assets/34624125/663fd68b-e100-484f-ad16-bf35a7a0856d)
![2023-08-04 (5)](https://github.com/Pangamma/PixelStacker/assets/34624125/16570234-bb8b-4a7f-88b5-ec5fd4479a91)
![2023-08-04 (4)](https://github.com/Pangamma/PixelStacker/assets/34624125/9736503f-08dd-431e-aeb8-3a3be6589d1e)

This only applies to coloured clay and not Clay itself which remains the same
![2023-08-04 (7)](https://github.com/Pangamma/PixelStacker/assets/34624125/b701ba6f-7892-4f9d-b3a1-6c53e7fde058)

**Comment by Pangamma** [comment]
Alright. I'll fix it. It'll take more space in the UI though.

**Comment by Pangamma** [comment]
Fixed
